### PR TITLE
Created a travis file for deploying on gh-pages.

### PR DESCRIPTION
**Pull request by RatanShreshtha**
A travis file has been added to the repository that publishes to gh-pages. Here is the reference for the file https://docs.travis-ci.com/user/deployment/pages/.

This PR address issue #44 .

### CODE REVIEW

**Comment by ananyo2012** [comment]
We are actually deploying to a server so we need to add a script in travis to auto deploy to that server. Let me check how to do that as well.

**Comment by RatanShreshtha** [comment]
@ananyo2012 I can change the travis.yml accordingly.

**Comment by ananyo2012** [comment]
@RatanShreshtha Yeah I will share the details soon

**Comment by ananyo2012** [comment]
Sorry I couldn't get time for looking at this. The thing I realized is we need automatic deployment more than having the CI. I am closing this PR as of now. But will reopen it when I am done my work on the deployment part

**Pull request closed without merging**
