### PR TITLE
Fix the border for keynote speakers #116

### PR DESCRIPTION
**Pull request by eddygta17**
Fixed issue with border on speakers pictures.
Border matches the profile exactly and stays as such

screenshot from 2018-06-10 11-36-53
screenshot from 2018-06-10 11-37-18
screenshot from 2018-06-10 11-37-40
screenshot from 2018-06-10 11-37-55

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
Thanks for your contribution @eddygta17 Please mention which issue you are trying to fix.

**Comment by ananyo2012** [comment]
@eddygta17 Please check [my comment](https://github.com/pythonindia/inpycon2018/issues/116#issuecomment-396141848) which is related to the PR you made.

**Comment by rajataaron** [comment]
This PR looks good according to design purpose just a small suggestion do text-align: centre for the speaker name and description.

**Comment by eddygta17** [comment]
screenshot from 2018-06-11 22-39-20
screenshot from 2018-06-11 22-40-22
screenshot from 2018-06-11 22-41-05

@ananyo2012 @rajataaron added commit after centering text

**Comment by ananyo2012** [comment]
LGTM. Merging this in.

**Pull request merged**
