### PR TITLE
Fixed border issue for speakers Issue #116

### PR DESCRIPTION
**Pull request by 2root2**
Issue #116 #120 
Used gradient border CSS instead of border image, so there shouldn't be any compatibility issue on any screen size . This should fix the issue once for all.
screen shot 2018-06-10 at 3 53 40 pm

### CODE REVIEW

**Comment by 2root2** [comment]
@vipulgupta2048 I've pushed my code to gh-pages branch. Here's the link [https://2root2.github.io/inpycon2018/](url)

**Comment by vipulgupta2048** [comment]
Thanks @2root2 
I like the changes you implemented. Tagging @pythonindia/pycon-2018-team for review

**Comment by ananyo2012** [comment]
@2roo2 Thanks for your contribution. Please check [my comment](https://github.com/pythonindia/inpycon2018/issues/116#issuecomment-396141848) regarding this. Also it is a good practice to comment on the issue before starting your work. So that you don't start working on an already claimed issue.

Though I like your approach in solving the issue please wait for sometime before #97 is merged

**Comment by ananyo2012** [comment]
We went on merging #120 since we wanted to stick to the original border image.

**Comment by ananyo2012** [comment]
Thanks for your contribution though. Please look at other open issues and comment on the issue from next time before starting.

**Pull request closed without merging**
