### PR TITLE
Updated the favicons and removed unused media

### LINKED ISSUE #68: [Urgent] Update/Delete all unused media
Due to recent changes in the venue, I think some of the media in the /icons and /img folder have become redundant. As it was either used for the conference being held in Bangalore or as dummy content. Favicons for the website need to be updated too if not done already.

### PR DESCRIPTION
**Pull request by parthsharma2**
Updated the favicons and removed unused media. This resolves #68

### CODE REVIEW

**Comment by ananyo2012** [comment]
@parthsharma2 Keep the images of speakers as we will be needing them later for speaker image diemensions. Update this one: https://github.com/pythonindia/inpycon2018/blob/master/img/favicon.png

**Comment by parthsharma2** [comment]
@ananyo2012 updated the PR

**Comment by ananyo2012** [comment]
@parthsharma2 Look carefully into the image. You missed to hollow the eyes of the image. Please update the images and update the PR again. Also check your email. I have sent you the psd , so it will be easier to edit. Thanks!

**Comment by parthsharma2** [comment]
@ananyo2012 fixed the image and updated the PR.

**Comment by ananyo2012** [comment]
@parthsharma2 Thanks! This looks good now. Merging it.

**Pull request merged**
