### PR TITLE
Time alignment fixed and designed accordion style for FAQ

### PR DESCRIPTION
**Pull request by tushar-nitave**
Fixed #55.

### CODE REVIEW

**Comment by realslimshanky** [comment]
@tushar-nitave please also edit the PR title and add that you have fixed accordian issue. Also link to issue no in description.

**Comment by ananyo2012** [comment]
@tushar-nitave Can we use a one shade lighter color in `.panel`, #3b3b3b maybe? The contrast is very little now. 

Now:
faq-panel

One shade lighter
image

**Comment by tushar-nitave** [comment]
Actually I tired using lighter shade but, I thought it will not look good. Anyway, I will change it. Any other suggestions?

**Comment by tushar-nitave** [comment]
@realslimshanky Yes I will do that as well.

**Comment by ananyo2012** [comment]
@chirag200666 @realslimshanky What are you views regarding the colour of the panel https://github.com/pythonindia/inpycon2018/pull/56#issuecomment-379475127 ?

**Comment by realslimshanky** [comment]
Lighter tone looks good. Text looks a little clearer on that one.

**Comment by ananyo2012** [comment]
@tushar-nitave I have updated the FAQs in #57 . Can you copy the content and rebase over the latest changes?

**Comment by ananyo2012** [comment]
Ah I guess you have pulled in the gh-pages branch. You need to pull from the master-branch.

**Comment by tushar-nitave** [comment]
@ananyo2012 Done with conflicts. Any changes?

**Comment by ananyo2012** [comment]
@tushar-nitave Looks good. Let people have a look, then we can move with the new faq page and replace it with the existing faq page.

**Pull request merged**
