### PR TITLE
Background change for venue-section

### PR DESCRIPTION
**Pull request by rajataaron**
I have added the background image for venue-section at bottom. Please have a look.

### CODE REVIEW

**Comment by rajataaron** [comment]
Oh sorry I forgot to add the screenshot here it is.
screenshot from 2018-06-14 09-46-17

**Comment by ananyo2012** [comment]
The color tone looks a bit different don't you think ?
image

**Comment by rajataaron** [comment]
It is because there is a white tone added on background image with a little saturation on it. And in previous image most of cloud is covered. I can do that on this image too.

**Comment by rajataaron** [comment]
Here is one more screenshot with lower tones. 
screenshot from 2018-06-14 16-40-25

**Comment by ananyo2012** [comment]
This one looks much better IMO. Can you update the PR with the image ?

**Comment by vipulgupta2048** [comment]
+1

**Comment by rajataaron** [comment]
PR updated with changes.
screenshot from 2018-06-15 10-36-36

**Comment by ananyo2012** [comment]
Merged

**Pull request merged**
