### PR TITLE
compressed sponsors images - tinified

### PR DESCRIPTION
**Pull request by bhansa**
- [x] Make sponsor images compressed and of similar dimensions  
- [x] Compress any jpeg images that can be done retaining the image visibility. Preferably make them png
 - [ ] Use caching for json data. Currently we are using sponsors.json to load data for sponsors. We need to cache the data on first load so that on subsequent loads the website loads faster

Partly solves #163

### CODE REVIEW

**Comment by bhansa** [comment]
compression report for timeline images:
image

**Comment by bhansa** [comment]
If we are not including them on the page, then it's fine to keep them the same way or we can just move them to a different folder altogether. 
One more thing can have a different image for Sidu ponnappa, the current one is not clear.

**Comment by bhansa** [comment]
Added the service worker code to cache js/css/json files, please review and suggest. Also if there is any other better approach please let me know.

**Comment by ananyo2012** [comment]
@bhansa Is there any way to measure how much the speed improved due to caching ? Also do the `cache-polyfill.js` ans `service-worker.js` needs to be kept outside the js folder ?

**Comment by bhansa** [comment]
service worker has to be in the root folder, so that's fine. We can check the speed using [lighthouse](https://developers.google.com/web/tools/lighthouse/) extension.

**Comment by ananyo2012** [comment]
Sorry for the delayed response. This lookd good to go. Here are the stats. There is a significant improve in perfromance

Before
before-optimization

After
after-optimaztion

**Comment by ananyo2012** [comment]
@bhansa Can you keep the changes of compressing images and the caching in 2 separate PRs. The first change is good to go. But we need to think a bit more about the caching stuff.

I observed that caching may cause the website to not reflect changes that we pushed recently and often we need to do a hard reload which we usually forget. So we need to expire the cached data after a time interval so that it tracks changes when we push them.

**Comment by bhansa** [comment]
@ananyo2012 I have reset this branch, please check and merge.

**Comment by ananyo2012** [comment]
Thanks @bhansa . Merging this. Do make another PR for caching part. We can continue discussion there.

**Pull request merged**
