### PR TITLE
Hide timeline buttons for large screen devices

### PR DESCRIPTION
**Pull request by samuellawrentz**
Fixes [#88](https://github.com/pythonindia/inpycon2018/issues/88)

Changes:

- Hide the timeline buttons for large screen devices using an existing media query.

Testing link:
https://samuellawrentz.github.io/inpycon2018/

### CODE REVIEW

**Comment by samuellawrentz** [comment]
Please find the working changes here
https://samuellawrentz.github.io/inpycon2018/

**Comment by realslimshanky** [comment]
@samuellawrentz please change your pr description and mention the issue link as well.

**Comment by samuellawrentz** [comment]
Updated.

**Comment by samuellawrentz** [comment]
@realslimshanky Can you please confirm whether the issue exists?

**Comment by realslimshanky** [comment]
It's fine now. Maybe it was a browser issue. Please squash your commits @samuellawrentz

**Comment by samuellawrentz** [comment]
I'm new to contribute. In fact, this is my first open source contribution. Can you please tell how to squash? Should I commit to the master branch? 

Thanks

**Comment by ananyo2012** [comment]
@samuellawrentz You should search the web for getting your answer. You can find lots of articles on squashing commits.

**Comment by ananyo2012** [comment]
@samuellawrentz Update on this ?

**Comment by samuellawrentz** [comment]
I read articles on squashing but I'm unable to perform the operation. It's throwing some kind of error. I'll check and update the PR today.

**Comment by ananyo2012** [comment]
What error are you facing? Can you share the error here ?

**Comment by samuellawrentz** [comment]
As you can see now the number of commits has increased to 8 from 2. For every squash I make, it is creating a normal commit along with a merge commit. Can you please check my git-log and tell if my commits are merged?

**Comment by ananyo2012** [comment]
@samuellawrentz What command are you using for squashing? Is it `git rebase -i` ?

**Comment by samuellawrentz** [comment]
Yeah, I used that command. Now my branch has 8 commits. I have not squashed commits before. I tried git rebase -i HEAD~3. After that I'm not sure what to do.

**Comment by samuellawrentz** [comment]
Really sorry guys, I accidentally deleted the branch. I shall get familiar with various git operations and make contributions. Thanks for helping me out and giving me a chance. All the best for the event.

**Pull request closed without merging**
