### PR TITLE
update location & dates of the conference.

### PR DESCRIPTION
**Pull request by chirag200666**
Resolving the issue: #42

### CODE REVIEW

**Comment by realslimshanky** [comment]
@CuriousLearner yes the confirmation about the venue and dates have been posted on the mailing list and the archive can be found [here](https://mail.python.org/pipermail/inpycon/2018-March/011884.html). I think we can proceed with merging this in.

**Comment by nithinmulley** [comment]
Just a thought so as to not confuse the audience. Not Reviewing the code. Not trying to add on delay here. 
- These content changes should be reflected along with updated artwork/logo which has Bengaluru in it.
- Content changes should also be reflected in the Timeline entries (probably 'js/content.js') which should go along with the proposed changes. Again Artwork/image needs to be relevant to new proposed location Hyderabad.
( completely optional - A new blog entry with any changes to the conference format as mentioned in the previous blog should go along with these changes or it can come later on)

**Comment by chirag200666** [comment]
@nithinmulley 
Made a PR for changes required in the timeline. The logo change will change will be done by webchirpy, hopefully by Monday.

**Comment by nithinmulley** [comment]
@chirag200666 
Nice! Logo and a picture relevant to Hyderabad in the timeline.
Thanks!

**Comment by chirag200666** [comment]
@nibrahim  @CuriousLearner  @realslimshanky @sayanchowdhury 
Guys what is the process of deploying the changes to the website? 
How about setting up CI/CD for the same?

**Comment by realslimshanky** [comment]
@chirag200666 one needs to access the server and pull changes from GitHub.

**Pull request merged**
