### PR TITLE
Added License Full Text of CC-BY-NC-SA 4.0 International

### PR DESCRIPTION
**Pull request by bauripalash**

### CODE REVIEW

**Comment by sayanchowdhury** [comment]
Do we really need to add the full text? The link mentions the License which contains human readable format and the full text of the license.

**Comment by bauripalash** [comment]
Actually `LICENSE` files such as `LICENCE.md` or `LICENCE.txt` usually contains the full text of licence. You can see it everywhere.

Now it depends on, what you guys think!👍

**Comment by ananyo2012** [comment]
@bauripalash I think the link is enough as it gives a summary of the license. Also the summary has the link to full license text.

**Comment by bauripalash** [comment]
Then , it's okay.
Thank you.

**Pull request closed without merging**
