### PR TITLE
added new button styles

### PR DESCRIPTION
**Pull request by bhansa**
Here is the update for buttons, please suggest if any edits, comments etc.
Regarding #102 
Preview: https://bhansa.github.io/inpycon2018/index.html

### CODE REVIEW

**Comment by ananyo2012** [comment]
Um I actually like the previous ones. Tagging @rajataaron for review here.

**Comment by inovizz** [comment]
I too like the previous style of buttons.

**Comment by rajataaron** [comment]
Same man previous button goes with the theme. Solid color buttons is not happening with website.
cc: @inovizz @ananyo2012

**Comment by bhansa** [comment]
Keeping the old design then, closing this PR.

**Pull request closed without merging**
